"start pathogen - must come first
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

let mapleader = ","

set go-=T                           "hide toolbar in mvim
set guifont=inconsolata:h15         "Set a better font
set number                          "Line Numbers
syntax on

set nobackup        
set noswapfile                      "Don't use swap files

"Indentation Options
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2


"Find and Replace Options
set hlsearch                        "highlights search results
set incsearch                       "shows search matches as you type
set showmatch                       "another search thing
set smartcase                       "if caps, watch case
set ignorecase                      "if all lowercase, ignore case 

nnoremap / /\v
vnoremap / /\bv
set gdefault
nnoremap <leader><space> :noh<cr>


"Line wrapping
nmap <leader>wrap :set wrap nolist linebreak<cr>
nmap <leader>nowrap :set nowrap nolist nolinebreak<cr>


set autoindent

if has("autocmd")
  filetype plugin indent on
endif

au FocusLost * :wa                  "save all files on window focus lost

function! Fix_markdown_for_tut()
    %s/\(<h\d\) id='.*'>/\1>/
    %s/<pre><code>/<pre class="" name="code">
    %s/<\/code>\(<\/pre>\)/\1/
endfunction

command! Fm call Fix_markdown_for_tut()
